{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "checkmk.serviceAccountName" . }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "checkmk.serviceAccountName" . }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  - storage.k8s.io
  - rbac.authorization.k8s.io
  - apps
  - extensions
  - batch
  - autoscaling
  - networking.k8s.io/v1beta1
  resources:
  - componentstatuses
  - nodes
  - nodes/proxy
  - services
  - pods
  - configmaps
  - secrets
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  - storageclasses
  - clusterroles
  - roles
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  - statefulsets
  - cronjobs
  - jobs
  - horizontalpodautoscalers
  verbs: ["get", "list"]
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
- nonResourceURLs:
  - /version
  - /healthz
  - /metrics
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "checkmk.serviceAccountName" . }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "checkmk.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "checkmk.serviceAccountName" . }}
{{- end }}
